### ISSUE TITLE
Example in swift?

### ISSUE THREAD

**Issue by alangue** [adad184/MMTweenAnimation#1]
Hi @adad184!!!
Very cool stuff you have done! 
Can you provide a quick example in swift? 
Thanks a lot!!

**Comment by adad184** [comment]
sorry, I'm not so skilled in swift, but you can bridge it from OC into swift.

you may check these  http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

**Comment by alangue** [comment]
Thank you for your reply! 

I already created the bridge, but it's about the syntax the problem for me...
I don't find the swift equivalent for this part:

anim.animationBlock = ^(double c,double d,double v,id target,MMTweenAnimation _animation)
{
    UIView *t = (UIView_)target;
    t.center = CGPointMake(t.x, v);
};

I'll do my researches ;)
